version: "3"

services:
  api:
    container_name: backend
    restart: always
    build: ./andromeda
    tmpfs: /api/uploads
    networks:
      - apinetwork
    expose:
      - "5000"
    environment:
      - BACKEND_WORKERS=${BACKEND_WORKERS}
      - ANDROMEDA_RGB_SATELLITE_URL=${ANDROMEDA_RGB_SATELLITE_URL}

  nginx:
    container_name: frontend
    restart: always
    build: ./andromeda-ui
    networks:
      - apinetwork
    expose:
      - "8080"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt

networks:
  apinetwork:
