name: Python package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9.16"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install libkrb5 for Kerberos on Linux
        if: contains(matrix.os, 'ubuntu')
        run: |
            sudo apt install -y libkrb5-dev
            pip install requests-kerberos  
      - name: Install dependencies
        working-directory: ./andromeda
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with pytest
        working-directory: ./andromeda
        run: |
          python -m unittest
